name: dpsite
channels:
  - defaults
  - conda-forge
dependencies:
  - natsort
  - conda-build
  - isort
  - pyyaml
  - requests
  - python-frontmatter
  - black
  - loguru
  - nh3
  - python-dotenv
  - coolname
  - beautifulsoup4
